import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { z } from "zod";
import { useState, type FormEvent } from "react";
import { ArrowLeft, Chrome, Eye, EyeOff } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const searchSchema=z.object({mode:z.enum(["login","signup","forgot"]).catch("login")});
const credentials=z.object({email:z.string().trim().email().max(255),password:z.string().min(8).max(72),fullName:z.string().trim().min(2).max(100).optional()});
export const Route=createFileRoute("/auth")({validateSearch:(s)=>searchSchema.parse(s),head:()=>({meta:[{title:"Log in or join — EARNPESA"},{name:"description",content:"Access your EARNPESA opportunities, referrals and wallet."},{property:"og:title",content:"Join EARNPESA"},{property:"og:description",content:"Create your account and start exploring verified opportunities."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Auth});
function Auth(){const {mode}=Route.useSearch();const navigate=useNavigate();const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const signup=mode==="signup";
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const fd=new FormData(e.currentTarget);const email=String(fd.get("email")??"");if(mode==="forgot"){const parsed=z.string().email().safeParse(email);if(!parsed.success){setMessage("Enter a valid email address.");setBusy(false);return;}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});setMessage(error?.message??"Check your email for the reset link.");setBusy(false);return;}const parsed=credentials.safeParse({email,password:String(fd.get("password")??""),fullName:signup?String(fd.get("fullName")??""):undefined});if(!parsed.success){setMessage("Check your details. Passwords need at least 8 characters.");setBusy(false);return;}if(signup){const {data,error}=await supabase.auth.signUp({email:parsed.data.email,password:parsed.data.password,options:{emailRedirectTo:window.location.origin, data:{full_name:parsed.data.fullName}}});if(error)setMessage(error.message);else if(!data.session)setMessage("Check your email to confirm your account.");else navigate({to:"/dashboard"});}else{const {error}=await supabase.auth.signInWithPassword({email:parsed.data.email,password:parsed.data.password});if(error)setMessage(error.message);else navigate({to:"/dashboard"});}setBusy(false);}
 async function google(){setBusy(true);const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin,extraParams:{prompt:"select_account"}});if(result.error){setMessage(result.error.message);setBusy(false);return;}if(!result.redirected)navigate({to:"/dashboard"});}
 return <main className="grid min-h-screen lg:grid-cols-[.9fr_1.1fr]"><section className="flex flex-col p-6 sm:p-10"><div><Brand/></div><div className="mx-auto flex w-full max-w-md flex-1 flex-col justify-center py-12"><Button variant="ghost" size="sm" className="mb-8 w-fit" onClick={()=>navigate({to:"/"})}><ArrowLeft/> Home</Button><p className="text-sm font-bold uppercase text-primary">{mode==="forgot"?"Account recovery":signup?"Start earning":"Welcome back"}</p><h1 className="mt-2 text-3xl font-extrabold">{mode==="forgot"?"Reset your password":signup?"Create your EARNPESA account":"Log in to your account"}</h1><p className="mt-2 text-sm text-muted-foreground">{signup?"Join Kenya's transparent digital opportunities marketplace.":"Manage opportunities, rewards and withdrawals."}</p>
 {mode!=="forgot"&&<Button variant="outline" size="lg" className="mt-7 w-full" onClick={google} disabled={busy}><Chrome/> Continue with Google</Button>}
 <form onSubmit={submit} className="mt-7 space-y-4">{signup&&<div><Label htmlFor="fullName">Full name</Label><Input id="fullName" name="fullName" className="mt-2 h-11" autoComplete="name" required maxLength={100}/></div>}<div><Label htmlFor="email">Email address</Label><Input id="email" name="email" type="email" className="mt-2 h-11" autoComplete="email" required maxLength={255}/></div>{mode!=="forgot"&&<div><Label htmlFor="password">Password</Label><div className="relative mt-2"><Input id="password" name="password" type={show?"text":"password"} className="h-11 pr-10" autoComplete={signup?"new-password":"current-password"} required minLength={8} maxLength={72}/><Button type="button" variant="ghost" size="icon" className="absolute right-1 top-1" onClick={()=>setShow(!show)} aria-label="Toggle password visibility">{show?<EyeOff/>:<Eye/>}</Button></div></div>}<Button className="h-11 w-full" disabled={busy}>{busy?"Please wait…":mode==="forgot"?"Send reset link":signup?"Create account":"Log in"}</Button></form>
 {message&&<p role="status" className="mt-4 rounded-md bg-muted p-3 text-sm">{message}</p>}<div className="mt-6 flex justify-between text-sm">{mode==="login"&&<button className="text-muted-foreground hover:text-foreground" onClick={()=>navigate({to:"/auth",search:{mode:"forgot"}})}>Forgot password?</button>}<button className="font-semibold text-primary" onClick={()=>navigate({to:"/auth",search:{mode:signup?"login":"signup"}})}>{signup?"Already a member? Log in":"New here? Create account"}</button></div></div></section><section className="hidden bg-foreground p-12 text-background lg:flex lg:flex-col lg:justify-between"><p className="max-w-lg font-display text-4xl font-extrabold leading-tight">A clear record of every action, verification and reward.</p><div className="grid grid-cols-2 gap-4"><div className="rounded-lg border border-background/15 p-5"><p className="text-3xl font-bold text-gold">100%</p><p className="mt-1 text-sm text-background/60">Transparent reward rules</p></div><div className="rounded-lg border border-background/15 p-5"><p className="text-3xl font-bold text-gold">KES</p><p className="mt-1 text-sm text-background/60">Kenya-first withdrawals</p></div></div></section></main>}